# Generated by Django 4.1.7 on 2023-03-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GoalID', models.CharField(max_length=60, unique=True, verbose_name='GoalID')),
                ('UserID', models.CharField(max_length=60, unique=True, verbose_name='UserID')),
                ('Name', models.CharField(max_length=70)),
                ('Description', models.CharField(max_length=70)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='crated')),
                ('DateTimeField', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]


    #login 
    #auth 
    #register validations
    #calendar connection 
    #Monday 13th  


